### ISSUE TITLE
Mobile Meta Tag 

### ISSUE THREAD

**Issue by Mikeysax** [kboygit/flippy#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by kboygit** [comment]
Hey Thanks mike,
        I will resolve the mobile issue once I'm done with my class . And get in touch with you as soon as possible

**Comment by kboygit** [comment]
mobile meta tag is being resolved and the font_url as well

**Comment by Mikeysax** [comment]
:+1:
